'use client'

import { useState } from 'react'
import { jsPDF } from 'jspdf'

const REPORTS = [
  { id: 'RPT-2026-04-W4', title: 'Laporan Mingguan — Minggu 4 April 2026', date: '28 Apr 2026', type: 'weekly', anomalies: 47, status: 'final' },
  { id: 'RPT-2026-04-W3', title: 'Laporan Mingguan — Minggu 3 April 2026', date: '21 Apr 2026', type: 'weekly', anomalies: 35, status: 'final' },
  { id: 'RPT-2026-04-W2', title: 'Laporan Mingguan — Minggu 2 April 2026', date: '14 Apr 2026', type: 'weekly', anomalies: 28, status: 'final' },
  { id: 'RPT-2026-03',    title: 'Laporan Bulanan — Maret 2026',           date: '01 Apr 2026', type: 'monthly', anomalies: 112, status: 'final' },
  { id: 'RPT-2026-02',    title: 'Laporan Bulanan — Februari 2026',        date: '01 Mar 2026', type: 'monthly', anomalies: 89, status: 'final' },
]

export default function ReportsPage() {
  const [startDate, setStartDate] = useState('2026-04-01')
  const [endDate, setEndDate] = useState('2026-04-30')
  const [isGenerating, setIsGenerating] = useState(false)
  const [pdfReady, setPdfReady] = useState(false)

  const handleGeneratePDF = async () => {
    setIsGenerating(true)
    setPdfReady(false)
    // Simulate Azure OpenAI PDF generation
    await new Promise(r => setTimeout(r, 2500))
    setIsGenerating(false)
    setPdfReady(true)
  }

  const handleDownloadPDF = () => {
    const doc = new jsPDF()
    
    // Add content to the PDF
    doc.setFontSize(18)
    doc.text('PANGANTRACE AI — RINGKASAN EKSEKUTIF', 14, 22)
    
    doc.setFontSize(11)
    doc.text(`Periode: ${startDate} s/d ${endDate}`, 14, 32)
    doc.text('Generated by: Azure OpenAI GPT-4o', 14, 38)
    doc.text(`Tanggal: ${new Date().toLocaleDateString('id-ID')}`, 14, 44)
    
    doc.setFontSize(14)
    doc.text('1. RINGKASAN ANOMALI', 14, 56)
    doc.setFontSize(11)
    doc.text('- Total anomali terdeteksi: 47 kejadian', 14, 64)
    doc.text('- Komoditas paling berisiko: Beras Premium', 14, 70)
    doc.text('- Provinsi terdampak: Jawa Timur, Jawa Barat, NTT', 14, 76)
    doc.text('- Severity tertinggi: CRITICAL (91.4/100)', 14, 82)
    
    doc.setFontSize(14)
    doc.text('2. ANALISIS AI', 14, 94)
    doc.setFontSize(11)
    const aiText = [
      'Sistem PanganTrace AI mendeteksi peningkatan anomali distribusi',
      'sebesar 34% dibanding periode sebelumnya. Pola utama yang terdeteksi:',
      '- Lonjakan harga tidak wajar pada Beras Premium di Jawa Timur (+18.5%)',
      '- Discrepancy volume distribusi >10% pada 3 distributor',
      '- Penurunan volume mendadak di titik distribusi NTT'
    ]
    doc.text(aiText, 14, 102)
    
    doc.setFontSize(14)
    doc.text('3. POTENSI KERUGIAN', 14, 134)
    doc.setFontSize(11)
    doc.text('Estimasi kebocoran subsidi: Rp 2.4 miliar', 14, 142)
    doc.text('Sumber utama: selisih volume pada layer distributor', 14, 148)
    
    doc.setFontSize(14)
    doc.text('4. REKOMENDASI TINDAKAN', 14, 160)
    doc.setFontSize(11)
    const actionText = [
      'a) Prioritaskan audit fisik pada distributor di Jawa Timur',
      'b) Verifikasi silang data pengiriman dengan Bulog regional',
      'c) Tingkatkan frekuensi monitoring untuk komoditas beras',
      'd) Koordinasi dengan Dinas Perdagangan provinsi terdampak'
    ]
    doc.text(actionText, 14, 168)
    
    doc.setFontSize(14)
    doc.text('5. STATUS MODEL AI', 14, 196)
    doc.setFontSize(11)
    doc.text('- Akurasi deteksi anomali: 94.7%', 14, 204)
    doc.text('- Model: Custom ML (Hosted on Azure App Service)', 14, 210)
    doc.text('- AI Insight: Azure OpenAI GPT-4o', 14, 216)
    
    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.text('© 2026 PanganTrace AI - Powered by Microsoft Azure', 14, 280)
    
    // Save the PDF
    doc.save(`PanganTrace_Report_${startDate}_${endDate}.pdf`)
  }

  return (
    <>
      <div className="page-header">
        <h2>📊 Laporan</h2>
        <p>Ringkasan periodik monitoring rantai pasok dan deteksi fraud — generated by Azure OpenAI</p>
      </div>

      {/* Report Generator */}
      <div className="card animate-in" style={{ marginBottom: 20 }}>
        <div className="card-header">
          <span className="card-title">
            <span className="material-symbols-outlined">auto_awesome</span>
            Generate Laporan Eksekutif
          </span>
          <span className="azure-badge">
            <span className="material-symbols-outlined" style={{ fontSize: 12 }}>psychology</span>
            Azure OpenAI GPT-4o
          </span>
        </div>

        <div style={{ display: 'flex', gap: 16, alignItems: 'end', flexWrap: 'wrap', marginBottom: 16 }}>
          <div>
            <label style={{ display: 'block', fontSize: '0.78rem', color: 'var(--text-tertiary)', marginBottom: 6, fontWeight: 500 }}>
              Tanggal Mulai
            </label>
            <input
              type="date"
              value={startDate}
              onChange={e => setStartDate(e.target.value)}
              style={{
                padding: '10px 14px',
                background: 'var(--bg-input)',
                border: '1px solid var(--border-default)',
                borderRadius: 'var(--radius-sm)',
                color: 'var(--text-primary)',
                fontSize: '0.88rem',
                fontFamily: 'inherit',
                outline: 'none',
                colorScheme: 'dark',
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', fontSize: '0.78rem', color: 'var(--text-tertiary)', marginBottom: 6, fontWeight: 500 }}>
              Tanggal Akhir
            </label>
            <input
              type="date"
              value={endDate}
              onChange={e => setEndDate(e.target.value)}
              style={{
                padding: '10px 14px',
                background: 'var(--bg-input)',
                border: '1px solid var(--border-default)',
                borderRadius: 'var(--radius-sm)',
                color: 'var(--text-primary)',
                fontSize: '0.88rem',
                fontFamily: 'inherit',
                outline: 'none',
                colorScheme: 'dark',
              }}
            />
          </div>
          <button
            onClick={handleGeneratePDF}
            disabled={isGenerating}
            style={{
              padding: '10px 24px',
              background: isGenerating ? 'var(--bg-elevated)' : 'linear-gradient(135deg, #8B5CF6, #3B82F6)',
              border: 'none',
              borderRadius: 'var(--radius-sm)',
              color: '#fff',
              fontSize: '0.88rem',
              fontWeight: 600,
              fontFamily: 'inherit',
              cursor: isGenerating ? 'wait' : 'pointer',
              display: 'flex', alignItems: 'center', gap: 8,
              transition: 'all 0.2s',
              boxShadow: isGenerating ? 'none' : '0 0 20px rgba(139, 92, 246, 0.2)',
              whiteSpace: 'nowrap',
            }}
          >
            <span className="material-symbols-outlined" style={{ fontSize: 18 }}>
              {isGenerating ? 'hourglass_top' : 'auto_awesome'}
            </span>
            {isGenerating ? 'Generating dengan AI...' : 'Generate Laporan'}
          </button>
        </div>

        {/* PDF Ready */}
        {pdfReady && (
          <div style={{
            padding: '16px 20px',
            background: 'rgba(16, 185, 129, 0.08)',
            border: '1px solid rgba(16, 185, 129, 0.2)',
            borderRadius: 'var(--radius-md)',
            display: 'flex', alignItems: 'center', gap: 14,
          }}>
            <div style={{
              width: 40, height: 40, borderRadius: 10,
              background: 'rgba(16, 185, 129, 0.15)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
            }}>
              <span className="material-symbols-outlined" style={{ fontSize: 22, color: '#10B981' }}>task</span>
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 600, fontSize: '0.88rem', color: '#10B981', marginBottom: 2 }}>
                Laporan siap di-download
              </div>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>
                Ringkasan eksekutif periode {startDate} s/d {endDate} telah di-generate oleh Azure OpenAI GPT-4o
              </div>
            </div>
            <button
              onClick={handleDownloadPDF}
              style={{
                padding: '8px 20px',
                background: 'linear-gradient(135deg, #10B981, #06B6D4)',
                border: 'none', borderRadius: 8,
                color: '#fff', fontSize: '0.82rem', fontWeight: 600,
                fontFamily: 'inherit', cursor: 'pointer',
                display: 'flex', alignItems: 'center', gap: 6,
                boxShadow: '0 2px 12px rgba(16, 185, 129, 0.3)',
              }}
            >
              <span className="material-symbols-outlined" style={{ fontSize: 16 }}>download</span>
              Download
            </button>
          </div>
        )}
      </div>

      {/* Report List */}
      <div className="card animate-in">
        <div className="card-header">
          <span className="card-title">
            <span className="material-symbols-outlined">description</span>
            Riwayat Laporan
          </span>
        </div>
        <table className="data-table" id="reports-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Judul</th>
              <th>Tipe</th>
              <th>Anomali</th>
              <th>Tanggal</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {REPORTS.map((r) => (
              <tr key={r.id}>
                <td style={{ fontFamily: 'monospace', fontSize: '0.78rem', color: 'var(--text-tertiary)' }}>{r.id}</td>
                <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{r.title}</td>
                <td>
                  <span className="commodity-tag">{r.type}</span>
                </td>
                <td>
                  <span style={{ fontWeight: 700, color: r.anomalies > 40 ? 'var(--risk-high)' : 'var(--text-secondary)' }}>
                    {r.anomalies}
                  </span>
                </td>
                <td style={{ color: 'var(--text-tertiary)' }}>{r.date}</td>
                <td>
                  <span style={{ color: 'var(--accent-emerald)', fontWeight: 500, fontSize: '0.78rem' }}>
                    {r.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  )
}
