'use client'

export default function ReportsPage() {
  const reports = [
    { id: 'RPT-2026-04-W4', title: 'Laporan Mingguan — Minggu 4 April 2026', date: '28 Apr 2026', type: 'weekly', anomalies: 47, status: 'final' },
    { id: 'RPT-2026-04-W3', title: 'Laporan Mingguan — Minggu 3 April 2026', date: '21 Apr 2026', type: 'weekly', anomalies: 35, status: 'final' },
    { id: 'RPT-2026-04-W2', title: 'Laporan Mingguan — Minggu 2 April 2026', date: '14 Apr 2026', type: 'weekly', anomalies: 28, status: 'final' },
    { id: 'RPT-2026-03',    title: 'Laporan Bulanan — Maret 2026',           date: '01 Apr 2026', type: 'monthly', anomalies: 112, status: 'final' },
    { id: 'RPT-2026-02',    title: 'Laporan Bulanan — Februari 2026',        date: '01 Mar 2026', type: 'monthly', anomalies: 89, status: 'final' },
  ]

  return (
    <>
      <div className="page-header">
        <h2>Laporan</h2>
        <p>Ringkasan periodik monitoring rantai pasok dan deteksi fraud — generated by Azure OpenAI</p>
      </div>

      <div className="card animate-in">
        <div className="card-header">
          <span className="card-title">
            <span className="material-symbols-outlined">description</span>
            Semua Laporan
          </span>
        </div>
        <table className="data-table" id="reports-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Judul</th>
              <th>Tipe</th>
              <th>Anomali</th>
              <th>Tanggal</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((r) => (
              <tr key={r.id}>
                <td style={{ fontFamily: 'monospace', fontSize: '0.78rem', color: 'var(--text-tertiary)' }}>{r.id}</td>
                <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{r.title}</td>
                <td>
                  <span className="commodity-tag">{r.type}</span>
                </td>
                <td>
                  <span style={{ fontWeight: 700, color: r.anomalies > 40 ? 'var(--risk-high)' : 'var(--text-secondary)' }}>
                    {r.anomalies}
                  </span>
                </td>
                <td style={{ color: 'var(--text-tertiary)' }}>{r.date}</td>
                <td>
                  <span style={{ color: 'var(--accent-emerald)', fontWeight: 500, fontSize: '0.78rem' }}>
                    {r.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  )
}
